// <auto-generated />
namespace Task_Manager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class statusDocuments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(statusDocuments));
        
        string IMigrationMetadata.Id
        {
            get { return "201707060741032_statusDocuments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
